<?php

namespace App\Support;

/**
 * Encyclopedia framing for compounds that are not covered by a dedicated
 * profile class. Copy is class language only: no doses, prices, invented
 * CAS numbers, reconstitution recipes, or product-path CTAs.
 */
class CatalogFraming
{
    /** @var array<string, array<string, mixed>>|null */
    private static ?array $byAlias = null;

    /**
     * @return array<string, mixed>|null
     */
    public static function find(?string $slug, ?string $name = null): ?array
    {
        self::boot();
        foreach ([$slug, $name] as $value) {
            $key = EncyclopediaSlug::normalize($value);
            if ($key === '') {
                continue;
            }
            if (isset(self::$byAlias[$key])) {
                return self::$byAlias[$key];
            }
            $hyphen = str_replace(' ', '-', $key);
            if (isset(self::$byAlias[$hyphen])) {
                return self::$byAlias[$hyphen];
            }
        }

        return null;
    }

    /**
     * @return list<array<string, mixed>>
     */
    public static function all(): array
    {
        return self::definitions();
    }

    private static function boot(): void
    {
        if (self::$byAlias !== null) {
            return;
        }
        self::$byAlias = [];
        foreach (self::definitions() as $def) {
            foreach ($def['aliases'] as $alias) {
                $key = EncyclopediaSlug::normalize($alias);
                self::$byAlias[$key] = $def;
                self::$byAlias[str_replace(' ', '-', $key)] = $def;
                self::$byAlias[str_replace('-', ' ', $key)] = $def;
            }
        }
    }

    /**
     * @return list<array<string, mixed>>
     */
    private static function definitions(): array
    {
        return [
            self::nonPeptide(
                ['methylene-blue', 'methylene blue'],
                'Methylene Blue',
                'What is Methylene Blue? Phenothiazine Dye',
                'Methylene blue (methylthioninium chloride) is a phenothiazine dye and small molecule. It is not a peptide. Research material is not ProvayBlue.',
                'What is methylene blue?',
                'Phenothiazine dye (methylthioninium chloride)',
                'Small Molecule',
                'Small-Molecule Research Compound',
                ['Small Molecule', 'Phenothiazine'],
                'Methylene blue is methylthioninium chloride, a phenothiazine dye and small molecule. It is not a peptide. ProvayBlue is the approved intravenous drug for acquired methemoglobinemia. Research-grade dye or powder sold under the methylene blue name is not ProvayBlue. This page does not give doses.',
                'The chloride salt is the form described by CAS 61-73-4 and formula C16H18ClN3S. That identity is a dye and a redox-active small molecule. It has no amino-acid sequence. The approved drug and a research-chemical listing are different presentations of the name.',
                'Methylthioninium chloride is a small molecule. Its clinical drug product is ProvayBlue injection for methemoglobinemia. This page does not restate a dose.',
                'Research methylene blue is not ProvayBlue and is not a peptide.',
                'Methylene blue is a phenothiazine small molecule, not a peptide. ProvayBlue is the approved injection. Research material is a separate presentation.',
                ['Methylene blue is methylthioninium chloride, a phenothiazine dye.', 'It is not a peptide.', 'ProvayBlue is the approved methemoglobinemia drug. Research material is not that drug.'],
                'Methylthioninium chloride participates in redox chemistry as a small molecule.',
                [['question' => 'Is methylene blue a peptide?', 'answer' => 'No. Methylene blue is methylthioninium chloride, a phenothiazine small molecule.']],
                'C16H18ClN3S',
                '319.85 g/mol',
                '61-73-4',
                'https://pubchem.ncbi.nlm.nih.gov/compound/6099',
            ),
            self::nonPeptide(
                ['nmn', 'nicotinamide mononucleotide'],
                'NMN',
                'What is NMN? NAD Precursor Nucleotide',
                'NMN is nicotinamide mononucleotide, a nucleotide and NAD precursor. It is not a peptide and it is not NAD+ itself.',
                'What is NMN?',
                'Nucleotide precursor of NAD+',
                'Nucleotide',
                'Nucleotide, Not a Peptide',
                ['Nucleotide', 'NAD Precursor'],
                'NMN (nicotinamide mononucleotide) is a nucleotide, formula C11H15N2O8P. It is a precursor of the coenzyme NAD+ and it is not a peptide. It is not NAD+ itself. The coenzyme page is /encyclopedia/nad. In 2022 the FDA stated that NMN is excluded from the dietary-supplement definition because it was authorized for investigation as a new drug, and that investigation was public, before it was marketed as a supplement. This page does not call NMN an approved drug or a dietary supplement, and it does not describe a later reversal of that position. No dose is given.',
                'NMN is one enzymatic step from <a href="/encyclopedia/nad">NAD+</a>. The link uses the live encyclopedia slug nad. Paths written as NAD+ or nad-plus are not used here. CAS 1094-61-7 identifies the nucleotide, not a peptide sequence.',
                'NMN is a nucleotide precursor. The FDA supplement position above is a regulatory classification, not an approval of NMN as a drug and not a statement that a research powder is a lawful supplement.',
                'NMN is not a peptide. Research-chemical NMN is not an approved drug product on the strength of the new-drug exclusion, and this page does not relabel it as a dietary supplement.',
                'NMN is a nucleotide precursor of NAD+. It is not a peptide. The FDA has treated it as excluded from the dietary-supplement definition. No dose is stated.',
                ['NMN is nicotinamide mononucleotide, a nucleotide.', 'It is not a peptide and it is not NAD+.', 'The NAD+ page is /encyclopedia/nad.', 'This page does not call NMN an approved drug or a dietary supplement.'],
                'NMN is converted toward NAD+ in nucleotide metabolism. It is not an amino-acid polymer.',
                [
                    ['question' => 'Is NMN a peptide?', 'answer' => 'No. NMN is a nucleotide, a precursor of NAD+. It is not a peptide.'],
                    ['question' => 'Is NMN the same as NAD+?', 'answer' => 'No. NAD+ is the dinucleotide coenzyme. Its page is /encyclopedia/nad.'],
                ],
                'C11H15N2O8P',
                '334.22 g/mol',
                '1094-61-7',
                'https://pubchem.ncbi.nlm.nih.gov/compound/14180',
                ['/encyclopedia/nad'],
            ),
            self::nonPeptide(
                ['acetic-acid', 'acetic acid'],
                'Acetic Acid',
                'What is Acetic Acid? Carboxylic Acid',
                'Acetic acid is a carboxylic acid and laboratory chemical. It is not a peptide. This page gives no mixing or reconstitution guidance.',
                'What is acetic acid?',
                'Carboxylic acid and laboratory chemical',
                'Laboratory Chemical',
                'Laboratory Chemical, Not a Peptide',
                ['Carboxylic Acid', 'Solvent'],
                'Acetic acid (ethanoic acid) is a carboxylic acid, formula C2H4O2, CAS 64-19-7. It is a laboratory chemical and solvent. It is not a peptide. This page does not give percentages, volumes, or reconstitution instructions.',
                'The molecule is a two-carbon carboxylic acid. Laboratories use it as a reagent and solvent. That use does not make it a peptide, and this entry does not describe how to dissolve another substance in it.',
                'No preparation chart is provided. Acetic acid is identified here only as a carboxylic acid.',
                'Acetic acid is not a peptide and not a drug monograph on this page.',
                'Acetic acid is a carboxylic acid. It is not a peptide. Mixing guidance is omitted on purpose.',
                ['Acetic acid is a carboxylic acid, not a peptide.', 'No reconstitution percentages or volumes are given.'],
                'Acetic acid is CH3COOH, a small-molecule carboxylic acid.',
                [['question' => 'Is acetic acid a peptide?', 'answer' => 'No. Acetic acid is a carboxylic acid. This page does not give reconstitution instructions.']],
                'C2H4O2',
                '60.05 g/mol',
                '64-19-7',
                'https://pubchem.ncbi.nlm.nih.gov/compound/176',
            ),
            self::nonPeptide(
                ['ibutamoren', 'mk-677', 'mk677', 'mk 677'],
                'Ibutamoren',
                'What is Ibutamoren? Ghrelin Mimetic',
                'Ibutamoren (MK-677) is a small-molecule ghrelin-receptor agonist. It is not a peptide. No dosing is given here.',
                'What is ibutamoren?',
                'Small-molecule ghrelin receptor (GHS-R1a) agonist',
                'Small Molecule',
                'Small-Molecule Ghrelin Mimetic',
                ['Small Molecule', 'Ghrelin Mimetic'],
                'Ibutamoren, also called MK-677, is an orally active small-molecule agonist of the ghrelin receptor GHS-R1a. It is a ghrelin mimetic. It is not a peptide and it is not a growth-hormone-releasing peptide. This page does not give a dose or a price. No CAS is stated.',
                'Growth-hormone secretagogue peptides such as GHRP-2 and ipamorelin are amino-acid ligands. Ibutamoren is a different chemical class: a synthetic small molecule that acts at the same receptor family. The live encyclopedia slug for this entry is Ibutamoren.',
                'Ibutamoren is discussed as a small-molecule pharmacology tool. No human dose is copied onto this page.',
                'Research-chemical ibutamoren is not an approved growth-hormone drug.',
                'Ibutamoren (MK-677) is a small-molecule ghrelin mimetic. It is not a peptide. No dose is stated.',
                ['Ibutamoren is MK-677, a small-molecule GHS-R1a agonist.', 'It is not a peptide.', 'No dose is given.'],
                'Ibutamoren binds the ghrelin receptor as a small molecule.',
                [['question' => 'Is ibutamoren a peptide?', 'answer' => 'No. Ibutamoren (MK-677) is a small-molecule ghrelin-receptor agonist.']],
            ),
            self::nonPeptide(
                ['hgh 191aa', 'hgh-191aa', 'hgh191aa'],
                'HGH 191AA',
                'What is HGH 191AA? Somatropin Protein',
                'HGH 191AA is somatropin, a 191-amino-acid growth-hormone protein. It is not a peptide. Research listings are not finished somatropin brands.',
                'What is HGH 191AA?',
                'Somatropin, a 191-amino-acid protein',
                'Protein',
                'Somatropin Protein',
                ['Protein', 'Somatropin'],
                'HGH 191AA refers to somatropin, recombinant human growth hormone, a 191-amino-acid protein. It is not a peptide. Finished prescription brands such as Genotropin, Norditropin, Humatrope, and Omnitrope are approved somatropin products. A research-catalog listing is not those brands. No dose is given. No CAS is stated.',
                'Somatropin is the recombinant protein that matches the 191-residue sequence of pituitary growth hormone. Calling that protein a short research peptide misstates its class. The public encyclopedia URL for this entry is /encyclopedia/hgh-191aa.',
                'Prescription somatropin is a labeled biologic or drug product. Research-grade material sold as HGH 191AA is not interchangeable with those brands.',
                'This page does not assign a CAS number and does not give a dose.',
                'HGH 191AA is somatropin, a 191-amino-acid protein, not a peptide. Research listings are not finished prescription brands.',
                ['Somatropin is a 191-amino-acid protein.', 'It is not a peptide.', 'Research listings are not Genotropin, Norditropin, Humatrope, or Omnitrope.'],
                'Somatropin is the recombinant growth-hormone protein. It signals as that protein, not as a short peptide.',
                [['question' => 'Is HGH 191AA a short peptide?', 'answer' => 'No. It is somatropin, a 191-amino-acid protein. Research listings are not the finished prescription brands.']],
            ),
            self::nonPeptide(
                ['ace-031', 'ace 031', 'ace031'],
                'ACE-031',
                'What is ACE-031? ActRIIB-Fc Biologic',
                'ACE-031 is an ActRIIB-Fc fusion biologic, not a peptide. No CAS is stated. Clinical development was discontinued.',
                'What is ACE-031?',
                'ActRIIB-Fc fusion biologic',
                'Fusion Biologic',
                'ActRIIB-Fc Biologic',
                ['Fusion Biologic', 'ActRIIB'],
                'ACE-031 is a fusion of the extracellular domain of activin receptor type IIB (ActRIIB) to an IgG Fc domain. It was developed by Acceleron as a ligand trap for myostatin and related TGF-beta family ligands. It is a biologic, not a peptide. Clinical development was discontinued. No CAS number and no molecular weight are stated on this page. No dose is given.',
                'An Fc fusion is a recombinant protein. It is not a short synthetic peptide, and a vendor CAS would be an invention if this page printed one. The program is not an approved medicine.',
                'ACE-031 is described only as a discontinued investigational biologic. No administration guidance is included.',
                'No CAS is assigned on this page. ACE-031 is not an approved drug.',
                'ACE-031 is an ActRIIB-Fc fusion biologic, not a peptide. Development was discontinued. No CAS is stated.',
                ['ACE-031 is an ActRIIB-Fc fusion protein.', 'It is not a peptide.', 'No CAS is stated.', 'Development was discontinued.'],
                'The ActRIIB extracellular domain binds ligands such as myostatin. The Fc domain is part of the same recombinant biologic.',
                [['question' => 'Is ACE-031 a short peptide?', 'answer' => 'No. ACE-031 is an ActRIIB-Fc fusion biologic. No CAS is stated here.']],
            ),
            self::peptide(
                ['oxytocin'],
                'Oxytocin',
                'What is Oxytocin? Nonapeptide Hormone',
                'Oxytocin is a cyclic nonapeptide hormone. Pitocin injection is the approved drug. Research powders are not Pitocin. No labor or fertility dosing is given.',
                'What is oxytocin?',
                'Cyclic nonapeptide hormone',
                'Peptide Hormone',
                'Peptide Hormone',
                ['Peptide Hormone', 'Oxytocin'],
                'Oxytocin is a cyclic nonapeptide hormone. Pitocin is the approved oxytocin injection used in obstetric care. Research powders and vials that use the oxytocin name are not Pitocin. This page does not give labor protocols, fertility doses, or unit amounts.',
                'The hormone is a nine-residue peptide with a disulfide bond. That peptide identity is accurate. The drug identity is separate: Pitocin is a finished injection, and a research-chemical powder is not that injection.',
                'No labor induction schedule and no fertility dose are described. The distinction on this page is Pitocin versus research material.',
                'Pitocin is a prescription oxytocin injection. Research oxytocin is not Pitocin.',
                'Oxytocin is a nonapeptide. Pitocin is the approved injection. Research powders are not Pitocin, and no dose is stated.',
                ['Oxytocin is a cyclic nonapeptide.', 'Pitocin is the approved oxytocin injection.', 'Research powders are not Pitocin.', 'No labor or fertility dose is given.'],
                'Oxytocin is the endogenous nonapeptide. Pitocin is a pharmaceutical presentation of oxytocin, not a research powder.',
                [['question' => 'Is research oxytocin the same as Pitocin?', 'answer' => 'No. Pitocin is the approved oxytocin injection. Research powders are not that drug. This page does not give labor or fertility doses.']],
                ['pitocin'],
            ),
            self::peptide(
                ['gonadorelin'],
                'Gonadorelin',
                'What is Gonadorelin? GnRH Decapeptide',
                'Gonadorelin is the GnRH decapeptide. Pharmaceutical gonadorelin, including historical Factrel, is not a research powder. No fertility dosing is given.',
                'What is gonadorelin?',
                'GnRH decapeptide',
                'Peptide Hormone',
                'Peptide Hormone',
                ['Peptide Hormone', 'GnRH'],
                'Gonadorelin is a synthetic decapeptide identical in sequence to gonadotropin-releasing hormone (GnRH). It is a peptide. Factrel was a pharmaceutical gonadorelin hydrochloride product used diagnostically. Research powders are not that pharmaceutical product. This page does not give fertility doses.',
                'The decapeptide sequence is the GnRH sequence. That does not turn a research-catalog vial into Factrel or into any current finished diagnostic product.',
                'No ovulation-induction protocol and no microgram amount are stated.',
                'Pharmaceutical gonadorelin and research-grade powder are different presentations. Factrel is the historical diagnostic name cited here, not a research powder.',
                'Gonadorelin is the GnRH decapeptide. Research material is not pharmaceutical gonadorelin. No fertility dose is given.',
                ['Gonadorelin is a GnRH decapeptide.', 'Factrel was a pharmaceutical diagnostic product.', 'Research powders are not that product.', 'No fertility dose is given.'],
                'Gonadorelin is the decapeptide ligand of the GnRH receptor.',
                [['question' => 'Is research gonadorelin the same as Factrel?', 'answer' => 'No. Factrel was a pharmaceutical gonadorelin product. Research powders are not that product. No fertility dose is given here.']],
                ['factrel'],
            ),
            self::nonPeptide(
                ['tesofensine'],
                'Tesofensine',
                'What is Tesofensine? Monoamine Reuptake Inhibitor',
                'Tesofensine is a small-molecule inhibitor of serotonin, norepinephrine, and dopamine reuptake. It is not a peptide.',
                'What is tesofensine?',
                'Small-molecule triple monoamine reuptake inhibitor',
                'Small Molecule',
                'Small-Molecule Research Compound',
                ['Small Molecule', 'Monoamine Reuptake Inhibitor'],
                'Tesofensine (NS2330) is a small molecule that inhibits reuptake of serotonin, norepinephrine, and dopamine. It is not a peptide. No dose is given. No CAS is stated.',
                'The compound was investigated as a monoamine reuptake inhibitor. That pharmacology is small-molecule neuroscience, not peptide chemistry.',
                'This page does not describe a weight-management dose or a price.',
                'Tesofensine is not an approved peptide drug. It is not a peptide at all.',
                'Tesofensine is a small-molecule monoamine reuptake inhibitor. It is not a peptide.',
                ['Tesofensine is NS2330, a small molecule.', 'It inhibits serotonin, norepinephrine, and dopamine reuptake.', 'It is not a peptide.'],
                'Tesofensine blocks reuptake of three monoamine transmitters. It is not an amino-acid hormone.',
                [['question' => 'Is tesofensine a peptide?', 'answer' => 'No. Tesofensine is a small-molecule monoamine reuptake inhibitor.']],
            ),
            self::nonPeptide(
                ['l-carnitine', 'l carnitine', 'lcarnitine'],
                'L-Carnitine',
                'What is L-Carnitine? Quaternary Ammonium Compound',
                'L-carnitine is a quaternary ammonium compound used in fatty-acid transport. It is not a peptide.',
                'What is L-carnitine?',
                'Quaternary ammonium compound',
                'Small Molecule',
                'Small Molecule, Not a Peptide',
                ['Small Molecule', 'Carnitine'],
                'L-carnitine is a quaternary ammonium compound, formula C7H15NO3, CAS 541-15-1. It carries long-chain fatty acids into mitochondria as acylcarnitines. It is not a peptide. No dose is given.',
                'Carnitine is built from lysine and methionine in the body, but the finished molecule is not an amino-acid polymer. A peptide is a chain of amino acids. L-carnitine is not that chain.',
                'This page identifies the chemical class only.',
                'L-carnitine is not a peptide and this entry is not a supplement dose chart.',
                'L-carnitine is a quaternary ammonium compound, not a peptide.',
                ['L-carnitine is a quaternary ammonium compound.', 'It participates in mitochondrial fatty-acid transport.', 'It is not a peptide.'],
                'L-carnitine forms acylcarnitines so long-chain fatty acids can enter mitochondria.',
                [['question' => 'Is L-carnitine a peptide?', 'answer' => 'No. L-carnitine is a quaternary ammonium compound, not an amino-acid polymer.']],
                'C7H15NO3',
                '161.20 g/mol',
                '541-15-1',
                'https://pubchem.ncbi.nlm.nih.gov/compound/10917',
            ),
            self::nonPeptide(
                ['vitamin b12', 'vitamin-b12', 'cobalamin'],
                'Vitamin B12',
                'What is Vitamin B12? Cobalamin',
                'Vitamin B12 is cobalamin, a cobalt corrin vitamin. It is not a peptide. No dosing is given on this page.',
                'What is vitamin B12?',
                'Cobalamin, a corrin vitamin',
                'Vitamin',
                'Vitamin, Not a Peptide',
                ['Vitamin', 'Cobalamin'],
                'Vitamin B12 is a family of cobalamins: corrin-ring molecules with a cobalt center. Cyanocobalamin, methylcobalamin, adenosylcobalamin, and hydroxocobalamin are forms of that vitamin. Cobalamin is not a peptide. The public URL for this entry is /encyclopedia/vitamin-b12. No dose is given. Cyanocobalamin, one form, is CAS 68-19-9.',
                'A corrin is not an amino-acid sequence. Encyclopedia copy that calls vitamin B12 a peptide misstates the chemical class.',
                'No injection schedule is stated. Research-grade cobalamin is not automatically a finished prescription cyanocobalamin product.',
                'Vitamin B12 is a vitamin. It is not a peptide.',
                'Vitamin B12 is cobalamin, a cobalt corrin vitamin, not a peptide.',
                ['Vitamin B12 is cobalamin.', 'It is a corrin vitamin with a cobalt center.', 'It is not a peptide.'],
                'Cobalamin is a cofactor vitamin. It is not a peptide hormone.',
                [['question' => 'Is vitamin B12 a peptide?', 'answer' => 'No. Vitamin B12 is cobalamin, a corrin vitamin.']],
                '',
                '',
                '68-19-9',
            ),
            self::nonPeptide(
                ['phosphate buffered saline', 'phosphate-buffered-saline', 'pbs'],
                'Phosphate Buffered Saline',
                'What is Phosphate-Buffered Saline? Salt Buffer',
                'Phosphate-buffered saline is an aqueous salt buffer used as a laboratory diluent. It is not a peptide. No buffer recipe is given.',
                'What is phosphate-buffered saline?',
                'Aqueous salt buffer and laboratory diluent',
                'Buffer',
                'Laboratory Buffer, Not a Peptide',
                ['Buffer', 'Diluent'],
                'Phosphate-buffered saline (PBS) is water containing sodium chloride and phosphate salts, adjusted near physiological pH. It is a laboratory buffer and diluent. It is not a peptide and it is not a drug. The public URL is /encyclopedia/phosphate-buffered-saline. A request for /encyclopedia/PBS redirects there when this category exists. This page does not give a molar recipe.',
                'PBS is a salt solution. It has no amino-acid sequence. Describing it as a peptide because it is stored near research peptides is a category error.',
                'No mixing table is provided.',
                'PBS is a buffer, not a peptide and not an active compound.',
                'Phosphate-buffered saline is a salt buffer. It is not a peptide. No recipe is given.',
                ['PBS is phosphate-buffered saline, a salt buffer.', 'It is a diluent, not a peptide.', 'No molar recipe is given.'],
                'The salts set ionic strength and pH. The liquid is a vehicle, not a signaling molecule.',
                [['question' => 'Is PBS a peptide?', 'answer' => 'No. Phosphate-buffered saline is a salt buffer. It is not a peptide, and this page does not give a buffer recipe.']],
            ),
            self::peptide(
                ['cerebrolysin'],
                'Cerebrolysin',
                'What is Cerebrolysin? Protein Hydrolysate',
                'Cerebrolysin is a porcine brain-protein hydrolysate, a mixture of peptides and amino acids. It is not one peptide.',
                'What is Cerebrolysin?',
                'Porcine brain-protein hydrolysate',
                'Hydrolysate',
                'Protein Hydrolysate',
                ['Hydrolysate', 'Mixture'],
                'Cerebrolysin is a porcine brain-derived protein hydrolysate. It contains a mixture of peptides and free amino acids. It is not one peptide with one sequence. No dose is given. No single CAS is stated, because a mixture does not have one peptide registry number on this page.',
                'A hydrolysate is the product of enzymatic cleavage of brain proteins. Publishing one sequence, one molecular weight, or one CAS for that mixture would invent an identity the material does not have.',
                'This page does not describe Cerebrolysin as a single research peptide and does not give an administration schedule.',
                'Cerebrolysin is a mixture. It is not one peptide.',
                'Cerebrolysin is a brain-protein hydrolysate, not one peptide.',
                ['Cerebrolysin is a porcine brain-protein hydrolysate.', 'It is a mixture of peptides and amino acids.', 'It is not one peptide.'],
                'The preparation is a hydrolysate. Biological papers discuss that mixture, not a single synthetic sequence.',
                [['question' => 'Is Cerebrolysin one peptide?', 'answer' => 'No. Cerebrolysin is a protein hydrolysate, a mixture. It is not one peptide.']],
                ['hydrolysate'],
                true,
            ),
            self::peptide(
                ['adalank'],
                'Adalank',
                'What is Adalank? Unsettled Marketplace Name',
                'Adalank is a marketplace name without one published structure. No CAS, formula, or sequence is stated on this page.',
                'What is Adalank?',
                'Marketplace name with unsettled identity',
                'Unsettled Identity',
                'Unsettled Marketplace Name',
                ['Unsettled Identity'],
                'Adalank is an unsettled marketplace name. Vendor accounts do not agree: some listings equate it with an acetylated selank analog, and others describe a different construct. This page does not choose among those accounts. No sequence, formula, molecular weight, or CAS is stated.',
                'A name that points at more than one claimed structure cannot be given a single chemical record here. Inventing a CAS or a sequence would pick a side the public literature on this page does not settle. The blend category that pairs the name with Adamax is a different slug and is not this monograph.',
                'No dose is given. The entry is an identity warning, not a protocol.',
                'Until a primary structure is settled, Adalank is not assigned a peptide sequence on this site.',
                'Adalank remains an unsettled marketplace name. No CAS and no structure are invented here.',
                ['The Adalank name is unsettled across marketplace listings.', 'No CAS is stated.', 'No sequence or formula is stated.'],
                'There is no single mechanism to assign while the structure itself is unsettled.',
                [['question' => 'What is the structure of Adalank?', 'answer' => 'This page does not state one. The marketplace name is unsettled, and no CAS or sequence is invented here.']],
                ['unsettled'],
                false,
            ),
            self::peptide(
                ['eloralintide', 'ly3841136'],
                'Eloralintide',
                'What is Eloralintide? Investigational Amylin Agonist',
                'Eloralintide is an investigational selective amylin receptor agonist. It is not a GLP-1 agonist and it is not an approved drug.',
                'What is eloralintide?',
                'Investigational selective amylin receptor agonist',
                'Investigational',
                'Investigational Amylin Agonist',
                ['Amylin Agonist', 'Investigational'],
                'Eloralintide (LY3841136) is an investigational selective amylin receptor agonist from Eli Lilly, described in the company literature as a peptide amylin mimetic. It is not a GLP-1 receptor agonist. It is not an approved drug. Research-chemical material that uses the name is not the investigational clinical product. No dose is given. No CAS is stated. No weight-change percentages from trials are repeated here.',
                'Amylin receptor agonism is a different class from GLP-1 receptor agonism. Lilly has reported phase 2 work and has described the molecule as investigational. Approval has not been granted on the basis of those reports.',
                'This page does not turn an investigational amylin agonist into a GLP-1 drug and does not give a dose.',
                'Eloralintide is investigational. It is not an approved GLP-1 medicine.',
                'Eloralintide is an investigational amylin receptor agonist, not a GLP-1 agonist, and not an approved drug.',
                ['Eloralintide is LY3841136, an investigational amylin receptor agonist.', 'It is not a GLP-1 receptor agonist.', 'It is not approved.', 'No dose is given.'],
                'Eloralintide is reported as a selective agonist at amylin receptors. That is not GLP-1 receptor agonism.',
                [['question' => 'Is eloralintide a GLP-1 drug?', 'answer' => 'No. Eloralintide is an investigational selective amylin receptor agonist. It is not a GLP-1 agonist and it is not an approved drug.']],
                ['amylin'],
                false,
            ),
            self::peptide(
                ['thymulin'],
                'Thymulin',
                'What is Thymulin? Zinc-Dependent Nonapeptide',
                'Thymulin is a zinc-dependent thymic nonapeptide. It is not thymosin alpha-1. No dosing is given here.',
                'What is thymulin?',
                'Zinc-dependent thymic nonapeptide',
                'Thymic Peptide',
                'Thymic Nonapeptide',
                ['Thymic Peptide', 'Zinc-Dependent'],
                'Thymulin, also called facteur thymique serique, is a thymic nonapeptide. Biological activity depends on zinc. It is not thymosin alpha-1 (thymalfasin), which is a different 28-residue thymic peptide. No dose is given. No CAS is stated.',
                'The thymulin sequence is a nine-residue peptide that binds zinc. Thymosin alpha-1 is a longer, distinct peptide. Sharing a thymic origin does not make them the same compound.',
                'This page separates thymulin from thymosin alpha-1 and does not give a dose.',
                'Thymulin is not thymosin alpha-1.',
                'Thymulin is a zinc-dependent nonapeptide and is not thymosin alpha-1.',
                ['Thymulin is a zinc-dependent thymic nonapeptide.', 'It is not thymosin alpha-1.', 'No dose is given.'],
                'Thymulin is active as a zinc complex. Thymosin alpha-1 does not share that identity.',
                [['question' => 'Is thymulin the same as thymosin alpha-1?', 'answer' => 'No. Thymulin is a zinc-dependent nonapeptide. Thymosin alpha-1 is a different peptide.']],
                ['thymosin'],
                false,
            ),
            self::nonPeptide(
                ['bam-15', 'bam15', 'bam 15'],
                'BAM15',
                'What is BAM15? Mitochondrial Uncoupler',
                'BAM15 is a small-molecule mitochondrial uncoupler. It is not a peptide. No dosing is given on this page.',
                'What is BAM15?',
                'Small-molecule mitochondrial protonophore',
                'Small Molecule',
                'Small-Molecule Research Compound',
                ['Small Molecule', 'Mitochondrial Uncoupler'],
                'BAM15 is a small-molecule mitochondrial protonophore. It uncouples oxidative phosphorylation in preclinical metabolism research. It is not a peptide. No dose is given. No CAS is stated.',
                'Mitochondrial uncouplers in this class are synthetic small molecules. They are not amino-acid chains, and encyclopedia stubs that call BAM15 a peptide are mislabeled.',
                'No study dose is copied here.',
                'BAM15 is not a peptide and not an approved drug on this page.',
                'BAM15 is a small-molecule mitochondrial uncoupler, not a peptide.',
                ['BAM15 is a mitochondrial uncoupler.', 'It is a small molecule.', 'It is not a peptide.'],
                'BAM15 lets protons cross the inner mitochondrial membrane, dissipating the proton gradient.',
                [['question' => 'Is BAM15 a peptide?', 'answer' => 'No. BAM15 is a small-molecule mitochondrial uncoupler.']],
            ),
            self::nonPeptide(
                ['sterile water', 'sterile-water'],
                'Sterile Water',
                'What is Sterile Water? Preservative-Free Diluent',
                'Sterile water is preservative-free water for injection, a diluent only. It is not a peptide. No mixing guidance is given.',
                'What is sterile water?',
                'Preservative-free sterile diluent',
                'Diluent',
                'Diluent, Not a Peptide',
                ['Diluent'],
                'Sterile water for injection is preservative-free water used as a diluent. It is not a peptide and it is not a drug. It is also not bacteriostatic water, which is a different diluent because it contains benzyl alcohol. The bacteriostatic-water page is /encyclopedia/bacteriostatic-water. This page does not give volumes or mixing charts. The public URL is /encyclopedia/sterile-water.',
                'Preservative-free sterile water and <a href="/encyclopedia/bacteriostatic-water">bacteriostatic water</a> are both diluents. Only the bacteriostatic article contains benzyl alcohol. Neither is a peptide.',
                'No reconstitution volume is stated.',
                'Sterile water is a diluent. It is not a peptide.',
                'Sterile water is a preservative-free diluent, not a peptide, and not bacteriostatic water.',
                ['Sterile water is preservative-free water for injection.', 'It is a diluent, not a peptide.', 'It is not bacteriostatic water.', 'No mixing chart is given.'],
                'Sterile water is a vehicle. It has no pharmacological target of its own on this page.',
                [['question' => 'Is sterile water a peptide?', 'answer' => 'No. It is a preservative-free diluent. This page does not give mixing volumes.']],
            ),
            self::peptide(
                ['thymosin beta-4 fragment 1-4', 'thymosin-beta-4-fragment-1-4', 'thymosin beta 4 fragment 1-4'],
                'Thymosin Beta-4 Fragment 1-4',
                'What is Thymosin Beta-4 Fragment 1-4? Ac-SDKP',
                'Thymosin beta-4 fragment 1-4 is the tetrapeptide Ac-SDKP. It is not TB-500 and not full thymosin beta-4.',
                'What is thymosin beta-4 fragment 1-4?',
                'Ac-SDKP, the N-terminal tetrapeptide of thymosin beta-4',
                'Tetrapeptide',
                'Tetrapeptide',
                ['Tetrapeptide', 'Ac-SDKP'],
                'Thymosin beta-4 fragment 1-4 is Ac-SDKP (N-acetyl-seryl-aspartyl-lysyl-proline), the acetylated N-terminal tetrapeptide of thymosin beta-4. It is not TB-500. TB-500, on its own page at /encyclopedia/TB-500, is a different thymosin beta-4 fragment used in the research market, commonly the actin-binding region rather than residues 1-4. Full-length thymosin beta-4 has no encyclopedia page on this site; /encyclopedia/thymosin-beta-4 returns 404. No dose is given.',
                'Ac-SDKP is a four-residue peptide. <a href="/encyclopedia/TB-500">TB-500</a> is not that tetrapeptide. Full thymosin beta-4 is a 43-residue peptide and is not this fragment. The public URL for this fragment is /encyclopedia/thymosin-beta-4-fragment-1-4.',
                'The three names are kept apart: Ac-SDKP, TB-500, and full thymosin beta-4. No dose connects them.',
                'This page is only fragment 1-4. It does not stand in for TB-500 or for full thymosin beta-4.',
                'Fragment 1-4 is Ac-SDKP. It is not TB-500 and not full thymosin beta-4.',
                ['This entry is Ac-SDKP, thymosin beta-4 residues 1-4.', 'It is not TB-500.', 'Full thymosin beta-4 has no page here.'],
                'Ac-SDKP is the N-terminal tetrapeptide. TB-500 refers to a different fragment.',
                [['question' => 'Is thymosin beta-4 fragment 1-4 the same as TB-500?', 'answer' => 'No. Fragment 1-4 is Ac-SDKP. TB-500 is a different thymosin beta-4 fragment. Full thymosin beta-4 has no encyclopedia page here.']],
                ['ac-sdkp', 'tb-500'],
                false,
            ),
            self::peptide(
                ['ghk-basic', 'ghk basic'],
                'GHK Basic',
                'What is GHK Basic? Copper-Free Tripeptide',
                'GHK basic is the copper-free tripeptide Gly-His-Lys. It is not the GHK-Cu copper complex.',
                'What is GHK basic?',
                'Copper-free tripeptide Gly-His-Lys',
                'Tripeptide',
                'Copper-Free Tripeptide',
                ['Tripeptide', 'GHK'],
                'GHK basic is glycyl-L-histidyl-L-lysine, the copper-free tripeptide. It is not GHK-Cu. GHK-Cu is the copper(II) complex and has its own page at /encyclopedia/GHK-Cu. Formula C14H24N6O4. No CAS is stated. No dose is given.',
                'The free tripeptide can bind copper, but the unbound peptide and the copper complex are different catalog items. The copper complex is documented at <a href="/encyclopedia/GHK-Cu">GHK-Cu</a>.',
                'This page is the copper-free tripeptide only.',
                'GHK basic is not sold on this page as GHK-Cu.',
                'GHK basic is the copper-free tripeptide Gly-His-Lys, not the GHK-Cu complex.',
                ['GHK basic is Gly-His-Lys without copper.', 'GHK-Cu is the copper complex, at /encyclopedia/GHK-Cu.', 'No dose is given.'],
                'GHK is the tripeptide Gly-His-Lys. GHK-Cu is that peptide bound to copper(II).',
                [['question' => 'Is GHK basic the same as GHK-Cu?', 'answer' => 'No. GHK basic is the copper-free tripeptide. GHK-Cu is the copper complex, at /encyclopedia/GHK-Cu.']],
                ['ghk-cu'],
                false,
                'C14H24N6O4',
                '340.38 g/mol',
            ),
            self::peptide(
                ['crystagen'],
                'Crystagen',
                'What is Crystagen? Short Synthetic Peptide',
                'Crystagen is a short synthetic peptide sold under a marketplace name. The CAS field is blank. No registry number is invented here.',
                'What is Crystagen?',
                'Short synthetic peptide, CAS not stated',
                'Short Peptide',
                'Short Peptide',
                ['Short Peptide'],
                'Crystagen is a marketplace name for a short synthetic peptide, often grouped with Khavinson-style bioregulators. The CAS field is blank. This page does not invent a registry number, a molecular formula, or a sequence.',
                'Where primary records do not pin a single CAS to the catalog name, leaving the field blank is the accurate choice. A vendor CAS is not copied here.',
                'No dose is given.',
                'The CAS field is blank. Crystagen is not given an invented registry number.',
                'Crystagen is a short synthetic peptide name. The CAS field is blank.',
                ['Crystagen is a short synthetic peptide marketplace name.', 'The CAS field is blank.', 'No sequence is invented on this page.'],
                'No mechanism is assigned beyond the class of a short synthetic peptide, because a specific sequence is not adopted here.',
                [['question' => 'What is the CAS number for Crystagen?', 'answer' => 'The CAS field is blank. This page does not invent a registry number.']],
                ['cas field is blank'],
                false,
            ),
            self::peptide(
                ['setmelanotide'],
                'Setmelanotide',
                'What is Setmelanotide? IMCIVREE MC4 Agonist',
                'Setmelanotide is the MC4 receptor agonist in IMCIVREE. It is not melanotan. Research material is not IMCIVREE. No dosing is given.',
                'What is setmelanotide?',
                'MC4 receptor agonist peptide in IMCIVREE',
                'Prescription Peptide',
                'Prescription MC4 Agonist',
                ['MC4 Agonist', 'IMCIVREE'],
                'Setmelanotide is an eight-residue cyclic peptide that agonizes the melanocortin-4 receptor. IMCIVREE is the approved setmelanotide injection, labeled for chronic weight management in specified genetic and syndromic obesities, including POMC, PCSK1, and LEPR deficiency and Bardet-Biedl syndrome. It is not melanotan I or melanotan II. Research vials are not IMCIVREE. No dose is given. No CAS is stated.',
                'Melanotan peptides are a different melanocortin story and are not IMCIVREE. Setmelanotide is the active ingredient of that approved injection. A research-chemical vial does not become IMCIVREE by sharing a receptor family.',
                'Labeled use belongs to IMCIVREE, the finished product. This page does not restate a dose and does not discuss compounding-committee votes.',
                'Research-grade setmelanotide is not IMCIVREE. IMCIVREE is the FDA-approved product.',
                'Setmelanotide is the MC4 agonist in IMCIVREE. It is not melanotan. Research material is not the approved injection. No dose is given.',
                ['Setmelanotide is the peptide in IMCIVREE, an MC4 receptor agonist.', 'It is not melanotan.', 'Research vials are not IMCIVREE.', 'No dose is given.'],
                'Setmelanotide agonizes the melanocortin-4 receptor. That is the mechanism of the approved IMCIVREE product, not of melanotan.',
                [['question' => 'Is setmelanotide the same as melanotan?', 'answer' => 'No. Setmelanotide is the MC4 receptor agonist in IMCIVREE. Melanotan is a different compound. Research vials are not IMCIVREE.']],
                ['imcivree'],
                false,
            ),
            self::peptide(
                ['teduglutide'],
                'Teduglutide',
                'What is Teduglutide? GATTEX GLP-2 Analog',
                'Teduglutide is the GLP-2 analog in GATTEX. It is not a GLP-1 agonist. Research material is not GATTEX. No dosing is given.',
                'What is teduglutide?',
                'GLP-2 analog peptide in GATTEX',
                'Prescription Peptide',
                'Prescription GLP-2 Analog',
                ['GLP-2 Analog', 'GATTEX'],
                'Teduglutide is a 33-residue analog of glucagon-like peptide-2, with an amino-acid substitution that distinguishes it from native GLP-2. GATTEX is the approved teduglutide product, labeled for short bowel syndrome in patients who depend on parenteral support. It is not a GLP-1 receptor agonist and it is not semaglutide or tirzepatide. Research vials are not GATTEX. No dose is given. No CAS is stated.',
                'GLP-2 and GLP-1 are different peptides and different receptors. GATTEX is a finished GLP-2 analog product. A research listing is not that product.',
                'This page does not give a dose and does not discuss compounding-committee votes.',
                'Research-grade teduglutide is not GATTEX.',
                'Teduglutide is the GLP-2 analog in GATTEX. It is not a GLP-1 agonist. Research material is not GATTEX.',
                ['Teduglutide is a GLP-2 analog.', 'GATTEX is the approved product.', 'It is not a GLP-1 agonist.', 'Research vials are not GATTEX.'],
                'Teduglutide acts as a GLP-2 analog. It is not a GLP-1 receptor agonist.',
                [['question' => 'Is teduglutide a GLP-1 drug?', 'answer' => 'No. Teduglutide is a GLP-2 analog. GATTEX is the approved product. Research vials are not GATTEX.']],
                ['gattex'],
                false,
            ),
            self::nonPeptide(
                ['9-me-bc', '9 me bc', '9-methyl-beta-carboline'],
                '9-Me-BC',
                'What is 9-Me-BC? Beta-Carboline',
                '9-Me-BC is 9-methyl-beta-carboline, a small molecule. It is not a peptide. No dosing is given here.',
                'What is 9-Me-BC?',
                '9-methyl-beta-carboline, a small molecule',
                'Small Molecule',
                'Small-Molecule Research Compound',
                ['Small Molecule', 'Beta-Carboline'],
                '9-Me-BC is 9-methyl-beta-carboline, a beta-carboline small molecule studied in preclinical neuroscience. It is not a peptide. No dose is given. No CAS is stated.',
                'Beta-carbolines are heterocyclic small molecules. They are not amino-acid sequences. The encyclopedia stub that calls 9-Me-BC a peptide mislabels the class.',
                'No administration amount is stated.',
                '9-Me-BC is not a peptide.',
                '9-Me-BC is a beta-carboline small molecule, not a peptide.',
                ['9-Me-BC is 9-methyl-beta-carboline.', 'It is a small molecule.', 'It is not a peptide.'],
                '9-Me-BC is a beta-carboline heterocycle, not a peptide ligand.',
                [['question' => 'Is 9-Me-BC a peptide?', 'answer' => 'No. 9-Me-BC is 9-methyl-beta-carboline, a small molecule.']],
            ),
            self::nonPeptide(
                ['bromantane'],
                'Bromantane',
                'What is Bromantane? Adamantane Derivative',
                'Bromantane is an adamantane-derived small molecule. It is not a peptide. No dosing is given here.',
                'What is bromantane?',
                'Adamantane-derived small molecule',
                'Small Molecule',
                'Small-Molecule Research Compound',
                ['Small Molecule', 'Adamantane'],
                'Bromantane is an adamantane derivative, a small molecule also known under the drug name Ladasten in some markets. It is not a peptide. No dose is given. No CAS is stated.',
                'Adamantane derivatives are cage hydrocarbons attached to an aryl amine in this series. That is small-molecule chemistry. It is not a peptide sequence.',
                'No dose from actoprotector literature is copied here.',
                'Bromantane is not a peptide.',
                'Bromantane is an adamantane-derived small molecule, not a peptide.',
                ['Bromantane is an adamantane derivative.', 'It is a small molecule.', 'It is not a peptide.'],
                'Bromantane is a synthetic small molecule, not an amino-acid polymer.',
                [['question' => 'Is bromantane a peptide?', 'answer' => 'No. Bromantane is an adamantane-derived small molecule.']],
            ),
            self::nonPeptide(
                ['salidroside'],
                'Salidroside',
                'What is Salidroside? Phenylpropanoid Glycoside',
                'Salidroside is a phenylpropanoid glycoside from Rhodiola. It is not a peptide. No dosing is given here.',
                'What is salidroside?',
                'Phenylpropanoid glycoside',
                'Glycoside',
                'Glycoside, Not a Peptide',
                ['Glycoside', 'Small Molecule'],
                'Salidroside is a phenylpropanoid glycoside, the glucoside of tyrosol, found in Rhodiola. Formula C14H20O7, CAS 10338-51-9. It is not a peptide. No dose is given.',
                'A glycoside is a sugar bound to a small-molecule aglycone. Salidroside is not a chain of amino acids.',
                'No extract dose or pure-compound dose is stated.',
                'Salidroside is not a peptide.',
                'Salidroside is a phenylpropanoid glycoside, not a peptide.',
                ['Salidroside is a tyrosol glucoside.', 'It is a glycoside, not a peptide.', 'No dose is given.'],
                'Salidroside is a plant glycoside. It is not a peptide hormone.',
                [['question' => 'Is salidroside a peptide?', 'answer' => 'No. Salidroside is a phenylpropanoid glycoside.']],
                'C14H20O7',
                '300.30 g/mol',
                '10338-51-9',
                'https://pubchem.ncbi.nlm.nih.gov/compound/159278',
            ),
            self::nonPeptide(
                ['spermidine'],
                'Spermidine',
                'What is Spermidine? Polyamine',
                'Spermidine is a polyamine involved in cell growth. It is not a peptide. No dosing is given here.',
                'What is spermidine?',
                'Polyamine',
                'Polyamine',
                'Polyamine, Not a Peptide',
                ['Polyamine', 'Small Molecule'],
                'Spermidine is a polyamine, formula C7H19N3, CAS 124-20-9. Cells use it in growth and autophagy-related research. It is not a peptide. No dose is given.',
                'The name resembles peptide language only because both are biological amines. Spermidine is a linear polyamine, not an amino-acid polymer.',
                'No supplement dose is stated.',
                'Spermidine is not a peptide.',
                'Spermidine is a polyamine, not a peptide.',
                ['Spermidine is a polyamine.', 'It is not a peptide.', 'No dose is given.'],
                'Spermidine is a polycationic polyamine. It does not have a peptide backbone.',
                [['question' => 'Is spermidine a peptide?', 'answer' => 'No. Spermidine is a polyamine.']],
                'C7H19N3',
                '145.25 g/mol',
                '124-20-9',
                'https://pubchem.ncbi.nlm.nih.gov/compound/1102',
            ),
            self::peptide(
                ['alpha-klotho lr', 'alpha-klotho-lr', 'alpha klotho lr'],
                'Alpha-Klotho LR',
                'What is Alpha-Klotho LR? Klotho Protein',
                'Alpha-Klotho LR is catalog language for alpha-Klotho, a protein. It is not a short peptide. The CAS field is blank.',
                'What is Alpha-Klotho LR?',
                'Alpha-Klotho protein, catalog name Alpha-Klotho LR',
                'Protein',
                'Klotho Protein',
                ['Protein', 'Klotho'],
                'Alpha-Klotho is a single-pass transmembrane protein and circulating factor encoded by KL. The catalog name on this page is Alpha-Klotho LR. It is a protein, not a peptide. The letters LR are left as part of that catalog name and are not expanded into a chemical modification. The CAS field is blank. No sequence and no molecular weight are invented. The public URL is /encyclopedia/alpha-klotho-lr. Research listings are not a finished Klotho biologic. No dose is given.',
                'Klotho protein biology is not short-peptide chemistry. Printing a CAS, a fragment sequence, or an expansion of LR would invent an identity this page does not have.',
                'No dose is given. The entry is the protein class plus the catalog name.',
                'The CAS field is blank. Alpha-Klotho LR is not given an invented registry number.',
                'Alpha-Klotho LR names the alpha-Klotho protein in this catalog. It is not a short peptide. The CAS field is blank.',
                ['Alpha-Klotho is a protein encoded by KL.', 'The catalog name keeps the letters LR without inventing a modification.', 'The CAS field is blank.', 'It is not a short peptide.'],
                'Alpha-Klotho is a protein. It is not a short synthetic peptide.',
                [['question' => 'Is Alpha-Klotho LR a short peptide?', 'answer' => 'No. Alpha-Klotho is a protein. The CAS field is blank, and LR is not expanded into a structure on this page.']],
                ['cas field is blank'],
                true,
            ),
            self::peptide(
                ['n-acetyl larazotide', 'n-acetyl-larazotide', 'n acetyl larazotide'],
                'N-Acetyl Larazotide',
                'What is Larazotide Acetate?',
                'The characterized compound is larazotide acetate, an octapeptide. This catalog title is not treated as a separate N-acetyl structure. No dose is given.',
                'What is larazotide acetate?',
                'Larazotide acetate, an octapeptide',
                'Peptide',
                'Larazotide Acetate',
                ['Peptide', 'Larazotide Acetate'],
                'The compound with a published identity in this area is larazotide acetate, an octapeptide studied as a zonulin antagonist, including under the code AT-1001. The catalog title N-Acetyl Larazotide is imprecise. This page does not invent an N-acetyl structure and does not describe a separate N-acetyl derivative. No CAS is stated. No dose is given. The public URL is /encyclopedia/n-acetyl-larazotide.',
                'Larazotide acetate is the acetate salt of the octapeptide. Adding an N-acetyl group in prose, without a primary record for this catalog item, would invent chemistry. The title words are kept only so the existing page can be found. The framing is larazotide acetate.',
                'No celiac-study dose is copied here. Research material is not an approved larazotide medicine. Larazotide acetate is not an approved drug.',
                'This page does not assign N-acetyl chemistry to the catalog name.',
                'Frame this entry as larazotide acetate, an octapeptide. Do not read the catalog title as a verified N-acetyl derivative.',
                ['The characterized compound is larazotide acetate.', 'The catalog title N-Acetyl Larazotide is not treated as a separate structure.', 'No N-acetyl chemistry is invented.', 'No dose is given.'],
                'Larazotide acetate is an octapeptide studied against zonulin-mediated tight-junction opening. That description is the acetate, not an invented N-acetyl analog.',
                [['question' => 'Is N-acetyl larazotide a distinct N-acetyl compound?', 'answer' => 'This page does not say so. The characterized compound is larazotide acetate. An N-acetyl structure is not invented here.']],
                ['larazotide acetate'],
                false,
            ),
            self::peptide(
                ['cortexin'],
                'Cortexin',
                'What is Cortexin? Cortical Polypeptide Fraction',
                'Cortexin is a bovine cerebral-cortex polypeptide fraction, a mixture. It is not one peptide. The CAS field is blank.',
                'What is Cortexin?',
                'Bovine cerebral-cortex polypeptide fraction',
                'Polypeptide Fraction',
                'Polypeptide Fraction',
                ['Polypeptide Fraction', 'Mixture'],
                'Cortexin is a polypeptide preparation obtained from the cerebral cortex of cattle. It is a mixture of peptide fractions, not one peptide with one sequence. The CAS field is blank. No formula and no single molecular weight are stated. No dose is given.',
                'A cortical extract or hydrolysate-style fraction contains many peptides. Assigning one CAS or one sequence would invent a single identity. The CAS field is blank for that reason.',
                'No administration schedule is given.',
                'Cortexin is a mixture. The CAS field is blank.',
                'Cortexin is a bovine cortical polypeptide fraction, not one peptide. The CAS field is blank.',
                ['Cortexin is a mixture of cortical polypeptides.', 'It is not one peptide.', 'The CAS field is blank.'],
                'The material is a polypeptide fraction. It does not have one mechanism tied to one sequence on this page.',
                [['question' => 'What is the CAS number for Cortexin?', 'answer' => 'The CAS field is blank. Cortexin is a polypeptide mixture, not one peptide with one registry number.']],
                ['cas field is blank'],
                true,
            ),
            self::peptide(
                ['hmg', 'human menopausal gonadotropin', 'menotropins'],
                'HMG',
                'What is HMG? Menotropins',
                'HMG here means menotropins, a mix of FSH and LH activity. It is not HMG-CoA and not hCG. Research vials are not the FDA product.',
                'What is HMG?',
                'Menotropins (FSH and LH activity)',
                'Glycoprotein Hormones',
                'Menotropins',
                ['Glycoprotein Hormones', 'Menotropins'],
                'On this page HMG means human menopausal gonadotropin, also called menotropins: a urinary preparation with follicle-stimulating hormone and luteinizing hormone activity. Menopur is an FDA-approved menotropins product. Research vials are not Menopur. HMG is not HMG-CoA, the mevalonate-pathway thioester, and it is not hCG. No dose is given.',
                'Three different strings collide in search. HMG-CoA is a small-molecule metabolic intermediate. hCG is a single glycoprotein hormone with its own page. Menotropins are a mixture of FSH and LH activities. Only the last meaning belongs to this slug.',
                'The approved product is the finished menotropins injection. A research vial is not that product. No dose is stated, and compounding-committee language is not used.',
                'Research-grade HMG is not Menopur. HMG is not HMG-CoA and not hCG.',
                'HMG on this page is menotropins. It is not HMG-CoA and not hCG. Research vials are not the FDA-approved product.',
                ['HMG means menotropins, FSH plus LH activity.', 'It is not HMG-CoA.', 'It is not hCG.', 'Research vials are not Menopur.'],
                'Menotropins supply FSH and LH activity. That is not HMG-CoA reductase biology and not hCG.',
                [['question' => 'Is HMG the same as hCG or HMG-CoA?', 'answer' => 'No. HMG on this page is menotropins. HMG-CoA is a different molecule. hCG is a different hormone. Research vials are not the approved menotropins product.']],
                ['menotropins'],
                false,
            ),
            self::peptide(
                ['teriparatide'],
                'Teriparatide',
                'What is Teriparatide? PTH Analog',
                'Teriparatide is a 34-residue parathyroid-hormone peptide. Forteo is the approved product. Research vials are not Forteo. No dosing is given.',
                'What is teriparatide?',
                'Parathyroid hormone amino acids 1-34',
                'Prescription Peptide',
                'Prescription PTH Analog',
                ['PTH Analog', 'Forteo'],
                'Teriparatide is recombinant parathyroid hormone residues 1-34, a 34-amino-acid peptide. Forteo is an approved teriparatide injection for osteoporosis in the populations named on its label. Research vials are not Forteo. No dose is given. No CAS is stated. Abaloparatide (Tymlos) is a different peptide and is not this entry.',
                'Forteo is a finished prescription product. A research-catalog vial of a PTH fragment is not that product. This page does not restate the labeled amount and does not discuss compounding-committee votes.',
                'Labeled use belongs to the approved teriparatide injection. No dose number is printed here.',
                'Research-grade teriparatide is not Forteo.',
                'Teriparatide is the PTH 1-34 peptide in Forteo. Research vials are not Forteo. No dose is given.',
                ['Teriparatide is parathyroid hormone residues 1-34.', 'Forteo is an approved teriparatide product.', 'Research vials are not Forteo.', 'No dose is given.'],
                'Teriparatide is the N-terminal 34 residues of parathyroid hormone, produced as a recombinant peptide.',
                [['question' => 'Is a research vial of teriparatide the same as Forteo?', 'answer' => 'No. Forteo is the approved teriparatide injection. Research vials are not that product. No dose is given here.']],
                ['forteo'],
                false,
            ),
            self::peptide(
                ['mif-1', 'mif1', 'mif 1'],
                'MIF-1',
                'What is MIF-1? Pro-Leu-Gly-NH2',
                'MIF-1 is the tripeptide Pro-Leu-Gly-NH2. It is not melanotan. No dosing is given here.',
                'What is MIF-1?',
                'Pro-Leu-Gly-NH2, melanocyte-inhibiting factor',
                'Tripeptide',
                'Tripeptide',
                ['Tripeptide', 'MIF-1'],
                'MIF-1 (melanocyte-inhibiting factor) is the tripeptide Pro-Leu-Gly-NH2, the C-terminal fragment of oxytocin. It is not melanotan I and it is not melanotan II. No dose is given. No CAS is stated.',
                'Melanotan peptides are synthetic melanocortin analogs. MIF-1 is a three-residue peptide from the oxytocin sequence. The names are not interchangeable.',
                'No melanocortin dose and no MIF-1 dose are stated.',
                'MIF-1 is not melanotan.',
                'MIF-1 is Pro-Leu-Gly-NH2. It is not melanotan.',
                ['MIF-1 is the tripeptide Pro-Leu-Gly-NH2.', 'It is the C-terminal fragment of oxytocin.', 'It is not melanotan.'],
                'MIF-1 is Pro-Leu-Gly-NH2. That sequence is not a melanotan peptide.',
                [['question' => 'Is MIF-1 the same as melanotan?', 'answer' => 'No. MIF-1 is Pro-Leu-Gly-NH2. Melanotan I and melanotan II are different peptides.']],
                ['melanotan'],
                false,
            ),
            self::peptide(
                ['vesilut'],
                'Vesilut',
                'What is Vesilut? Glu-Asp Dipeptide',
                'Vesilut is the dipeptide Glu-Asp. It is not Vesugen (Lys-Glu-Asp) unless a certificate of analysis for that lot says otherwise.',
                'What is Vesilut?',
                'Dipeptide Glu-Asp',
                'Dipeptide',
                'Dipeptide',
                ['Dipeptide', 'Vesilut'],
                'Vesilut is the dipeptide Glu-Asp. Vesugen is a different peptide, Lys-Glu-Asp, and has its own page. The two sequences stay distinct unless a certificate of analysis for a specific lot shows they are the same material. No CAS is stated. No dose is given.',
                'Glu-Asp is two residues. Lys-Glu-Asp is three residues and is the sequence associated with Vesugen, not with Vesilut. A shared vendor style does not merge the sequences.',
                'No dose is given. Identity follows the sequence, not a blended product name.',
                'Vesilut is not described as Vesugen on this page.',
                'Vesilut is Glu-Asp. Vesugen is Lys-Glu-Asp. They are kept distinct.',
                ['Vesilut is the dipeptide Glu-Asp.', 'Vesugen is Lys-Glu-Asp.', 'They are different peptides unless a lot COA says otherwise.'],
                'Vesilut is Glu-Asp. That dipeptide is not the Vesugen tripeptide.',
                [['question' => 'Is Vesilut the same as Vesugen?', 'answer' => 'No. Vesilut is Glu-Asp. Vesugen is Lys-Glu-Asp. Treat them as the same material only when a certificate of analysis for that lot says so.']],
                ['glu-asp'],
                false,
            ),
            self::peptide(
                ['vesugen'],
                'Vesugen',
                'What is Vesugen? Lys-Glu-Asp Tripeptide',
                'Vesugen is the tripeptide Lys-Glu-Asp. It is not Vesilut (Glu-Asp) unless a certificate of analysis for that lot says otherwise.',
                'What is Vesugen?',
                'Tripeptide Lys-Glu-Asp',
                'Tripeptide',
                'Tripeptide',
                ['Tripeptide', 'Vesugen'],
                'Vesugen is the tripeptide Lys-Glu-Asp. Vesilut is a different peptide, the dipeptide Glu-Asp. The sequences stay distinct unless a certificate of analysis for a specific lot shows they are the same material. No CAS is stated. No dose is given.',
                'Adding the N-terminal lysine changes the sequence. Vesugen is not the Vesilut dipeptide. Both names appear in bioregulator catalogs, and that shared context is why the pages are easy to merge. They are not merged here.',
                'No dose is given.',
                'Vesugen is not described as Vesilut on this page.',
                'Vesugen is Lys-Glu-Asp. Vesilut is Glu-Asp. They are kept distinct.',
                ['Vesugen is Lys-Glu-Asp.', 'Vesilut is Glu-Asp.', 'They are different peptides unless a lot COA says otherwise.'],
                'Vesugen is the tripeptide Lys-Glu-Asp.',
                [['question' => 'Is Vesugen the same as Vesilut?', 'answer' => 'No. Vesugen is Lys-Glu-Asp. Vesilut is Glu-Asp. A certificate of analysis would have to show otherwise for a specific lot.']],
                ['lys-glu-asp'],
                false,
            ),
            self::peptide(
                ['pnc-28', 'pnc28', 'pnc 28'],
                'PNC-28',
                'What is PNC-28? p53-Derived Peptide',
                'PNC-28 is a p53-derived peptide attached to a penetration sequence. Clinical evidence is thin. It is not an approved cancer treatment.',
                'What is PNC-28?',
                'p53-derived peptide with a penetration sequence',
                'Research Peptide',
                'Research Peptide',
                ['Research Peptide', 'p53 Fragment'],
                'PNC-28 is a research peptide built from residues 17-26 of p53 attached to a cell-penetration sequence. Published work is preclinical, with thin clinical evidence. It is not an approved cancer drug. This page does not describe it as a cure. No dose is given. No CAS is stated.',
                'A p53 fragment is a laboratory construct. Case reports and preclinical papers do not establish an approved oncology indication. Language that calls PNC-28 a cancer cure overclaims the record.',
                'No treatment protocol is described. The clinical record is thin, and this page does not fill that gap with a claim.',
                'PNC-28 is not an approved cancer therapy.',
                'PNC-28 is a p53-derived research peptide. Evidence in humans is thin. It is not described here as a cure.',
                ['PNC-28 is a p53 17-26 peptide with a penetration sequence.', 'Clinical evidence is thin.', 'It is not an approved cancer treatment and is not described as a cure.'],
                'The peptide is studied for membrane effects in preclinical cancer models. Those models are not an approved treatment.',
                [['question' => 'Does PNC-28 cure cancer?', 'answer' => 'This page does not say that. PNC-28 is a research peptide with thin clinical evidence. It is not an approved cancer treatment.']],
                ['thin'],
                false,
            ),
        ];
    }

    /**
     * @param  list<string>  $aliases
     * @param  list<string>  $tags
     * @param  list<string>  $keyPoints
     * @param  list<array{question: string, answer: string}>  $faqs
     * @param  list<string>  $markers
     * @return array<string, mixed>
     */
    private static function nonPeptide(
        array $aliases,
        string $name,
        string $seoTitle,
        string $seoDescription,
        string $h1,
        string $subtitle,
        string $tag,
        string $eyebrow,
        array $tags,
        string $overview,
        string $background,
        string $human,
        string $regulatory,
        string $conclusion,
        array $keyPoints,
        string $how,
        array $faqs,
        string $formula = '',
        string $mw = '',
        string $cas = '',
        ?string $researchUrl = null,
        array $markers = [],
    ): array {
        return self::entry($aliases, $name, $seoTitle, $seoDescription, $h1, $subtitle, $tag, $eyebrow, $tags, $overview, $background, $human, $regulatory, $conclusion, $keyPoints, $how, $faqs, true, $markers, $formula, $mw, $cas, $researchUrl);
    }

    /**
     * @param  list<string>  $aliases
     * @param  list<string>  $tags
     * @param  list<string>  $keyPoints
     * @param  list<array{question: string, answer: string}>  $faqs
     * @param  list<string>  $markers
     * @return array<string, mixed>
     */
    private static function peptide(
        array $aliases,
        string $name,
        string $seoTitle,
        string $seoDescription,
        string $h1,
        string $subtitle,
        string $tag,
        string $eyebrow,
        array $tags,
        string $overview,
        string $background,
        string $human,
        string $regulatory,
        string $conclusion,
        array $keyPoints,
        string $how,
        array $faqs,
        array $markers,
        bool $rejectsPeptide = false,
        string $formula = '',
        string $mw = '',
        string $cas = '',
        ?string $researchUrl = null,
    ): array {
        return self::entry($aliases, $name, $seoTitle, $seoDescription, $h1, $subtitle, $tag, $eyebrow, $tags, $overview, $background, $human, $regulatory, $conclusion, $keyPoints, $how, $faqs, $rejectsPeptide, $markers, $formula, $mw, $cas, $researchUrl);
    }

    /**
     * @param  list<string>  $aliases
     * @param  list<string>  $tags
     * @param  list<string>  $keyPoints
     * @param  list<array{question: string, answer: string}>  $faqs
     * @param  list<string>  $markers
     * @return array<string, mixed>
     */
    private static function entry(
        array $aliases,
        string $name,
        string $seoTitle,
        string $seoDescription,
        string $h1,
        string $subtitle,
        string $tag,
        string $eyebrow,
        array $tags,
        string $overview,
        string $background,
        string $human,
        string $regulatory,
        string $conclusion,
        array $keyPoints,
        string $how,
        array $faqs,
        bool $rejectsPeptide,
        array $markers,
        string $formula,
        string $mw,
        string $cas,
        ?string $researchUrl,
    ): array {
        return [
            'aliases' => $aliases,
            'name' => $name,
            'seoTitle' => $seoTitle,
            'seoDescription' => $seoDescription,
            'h1' => $h1,
            'subtitle' => $subtitle,
            'tag' => $tag,
            'eyebrow' => $eyebrow,
            'tags' => $tags,
            'overview' => $overview,
            'background' => $background,
            'mechanismIntro' => $how,
            'items' => $keyPoints,
            'findings' => [[
                'title' => 'Class',
                'description' => $conclusion,
            ]],
            'human' => $human,
            'regulatory' => $regulatory,
            'conclusion' => $conclusion,
            'keyPoints' => $keyPoints,
            'areas' => [[
                'name' => $tag,
                'description' => $subtitle,
            ]],
            'applications' => [[
                'title' => $tag,
                'description' => $subtitle,
            ]],
            'how' => $how,
            'faqs' => $faqs,
            'uses' => [$tag],
            'rejectsPeptide' => $rejectsPeptide,
            'markers' => $markers,
            'formula' => $formula,
            'mw' => $mw,
            'cas' => $cas,
            'researchUrl' => $researchUrl,
            'institution' => null,
            'preserves' => false,
            'phrases' => [],
        ];
    }
}
